name: answer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cached_network_image: ^3.2.3
  chat_gpt_sdk: ^2.0.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter: 
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_easyloading: ^3.0.5
  flutter_highlight: ^0.7.0
  flutter_launcher_icons: ^0.12.0
  flutter_mailer: ^2.0.2
  flutter_markdown: ^0.6.14
  flutter_native_splash: ^2.2.18
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
  get: ^4.6.5
  highlight: ^0.7.0
  hive_flutter: ^1.1.0
  http: ^0.13.5
  in_app_review: ^2.0.6
  intl: ^0.18.0
  markdown: ^7.0.1
  path: ^1.8.2
  path_provider: ^2.0.13
  pretty_dio_logger: ^1.3.1
  share_plus: ^6.3.1
  sqflite: ^2.2.5
  url_launcher: ^6.1.10

dev_dependencies: 
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  drift_dev: ^2.4.1
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-white.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-green.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo-green.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo-green.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo-green.png"